FROM ubuntu:24.04
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN apt-get update && apt-get install -y \
      make npm

ENV LC_ALL="en_US.UTF-8"
USER ubuntu

WORKDIR /usr/src/app
RUN mkdir frontend

# Python dependencies
RUN --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=cache,target=/home/ubuntu/.cache/uv,uid=1000 \
    uv sync --frozen --no-install-project

# Node.js dependencies
ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN --mount=type=bind,source=frontend/package.json,target=frontend/package.json \
    --mount=type=bind,source=frontend/package-lock.json,target=frontend/package-lock.json \
    --mount=type=cache,target=/home/ubuntu/.npm,uid=1000 \
    cd frontend && npm ci

COPY --chown=ubuntu:ubuntu . .
RUN cd frontend && npm run build
CMD cd example && uv run fava --host 0.0.0.0 example.beancount
