name: Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Start browser
      run: make start-browser

    - name: Install dependencies
      run: make deps

    - name: Start Fava
      run: make run &

    - name: Run tests
      run: make test
